# Generated by Django 4.1.3 on 2022-11-12 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_servicetype_service_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date_created",
            field=models.DateField(default=datetime.date(2022, 11, 12)),
        ),
    ]
