# Generated by Django 4.1.3 on 2022-11-12 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_booking_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date_created",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 11, 12, 13, 35, 47, 202858, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="date_created",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 11, 12, 13, 35, 47, 202858, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
