# Generated by Django 4.1.3 on 2022-11-12 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_booking_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date_created",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="date_created",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
